# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type_of_game', models.CharField(choices=[('t', 'Duration'), ('d', 'Distance')], help_text='Particular game type - this determines what is presented back to the users app', max_length=1)),
                ('number_of_reps', models.PositiveSmallIntegerField(default=1, help_text='How many times to do this exercise')),
                ('distance', models.FloatField(blank=True, help_text='Through distance in cm', null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, help_text='Time in seconds for this exercise', null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score for this exercise per rep', null=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='What this plan aims to achieve for the patient', null=True)),
                ('session_count', models.PositiveSmallIntegerField(blank=True, default=1, help_text='How often the patient should do this plan daily', null=True)),
                ('start', models.DateTimeField(blank=True, help_text='When this treatment plan begins', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='When this treatment plan ends, if at all', null=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False, help_text='Whether or not this exercise is a required part of the plan')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Plan')),
            ],
            options={
                'ordering': ('order', 'exercise__name'),
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Plan')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(help_text='A plan is composed of multiple exercises which may be in order', through='exercise.PlanExercise', to='exercise.Exercise'),
        ),
        migrations.AddField(
            model_name='plan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
