# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_exercise_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight of object in Kilograms', null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='distance',
            field=models.FloatField(blank=True, help_text='Through distance in cm', null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Time in seconds for this exercise', null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='number_of_reps',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many times to do this exercise'),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score for this exercise per rep', null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight of object in Kilograms', null=True),
        ),
    ]
