# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20170126_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='number_of_reps',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many times to do this', null=True),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='number_of_reps',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many times to do this', null=True),
        ),
    ]
