# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_planexercise_additional_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveSmallIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.PlanExercise')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='plan',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
