# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20170126_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciserecord',
            options={},
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this plan as displayed to the patient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='patient',
            field=models.ForeignKey(help_text='Choose who this plan is for', on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='therapist',
            field=models.ForeignKey(help_text='Choose a therapist overseeing this treatment plan', on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='additional_description',
            field=models.TextField(blank=True, help_text='Add any patient specific information for this exercise. It will be appended to the instructions', null=True),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='exercise',
            field=models.ForeignKey(help_text='Select an exercise to use as a basis for this plan', on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='optional',
            field=models.BooleanField(default=False, help_text='Whether or not this exercise is a required part of the plan for completeness'),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='You can use this to customize the order this exercise appears in the plan', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='exerciserecord',
            unique_together=set([('exercise', 'start')]),
        ),
    ]
