# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_exercise_steps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciserecord',
            options={'ordering': ('start', 'end')},
        ),
        migrations.AddField(
            model_name='exercise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
