# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_auto_20170127_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tag',
            field=models.CharField(blank=True, choices=[('a', 'Android'), ('i', 'iOS')], help_text='Used to filter this to a particular platform if required (for Demo)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='tag',
            field=models.CharField(blank=True, choices=[('a', 'Android'), ('i', 'iOS')], help_text='Used to filter this to a particular platform if required (for Demo)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, choices=[('a', 'Android'), ('i', 'iOS')], help_text='Used to filter this to a particular platform if required (for Demo)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='tag',
            field=models.CharField(blank=True, choices=[('a', 'Android'), ('i', 'iOS')], help_text='Used to filter this to a particular platform if required (for Demo)', max_length=1, null=True),
        ),
    ]
